### ISSUE TITLE
Editing in yaml editor does not reflect changes in UI

### ISSUE THREAD

**Issue by codeasashu** [codeasashu/react-openapi-designer#13]
Editor changes are working fine and are reflected instantly in the YAML content editor.
However, the same is not working vice versa.  Yaml content editor changes are not reflecting in the UI

**Comment by claudiohs-inditex** [comment]
I testing this point need to be bi-directional, if you change the code it need to be reflected into the UI, a similar functionality than you change the code in the swagger.editor.com and it's reflected into the documentation.

**Comment by codeasashu** [comment]
@claudiohs-inditex This PR should fix it. Tests aren't added yet, so it can have issues, but I am merging for the sake of usage
