### ISSUE TITLE
Unable to add security

### ISSUE THREAD

**Issue by sandeep2rawat** [codeasashu/react-openapi-designer#18]
Security button on the path page is not working.

Nothing happens on clicking the `+ Security` button.

 ![image](https://user-images.githubusercontent.com/88418157/148633858-19dd184e-7432-468d-b708-f4dd27db903d.png)

**Comment by codeasashu** [comment]
@sandeep2rawat Thanks for the issue. Added a PR. This should be fixed in ver 0.7.0
